### ISSUE TITLE
there two gatsby-plugin-google-adsense in npmjs

### ISSUE THREAD

**Issue by xiyizhou** [IsAmrish/gatsby-plugin-google-adsense#2]
hi, there.
I like your gatsby-plugin-google-adsense, but there another  in npmjs.

when I try Install it as `$ npm install -S gatsby-plugin-disqus` , Actually， I install this one `https://www.npmjs.com/package/gatsby-plugin-google-adsense`. it has been deprecated.

Then ,I try `@isamrish/gatsby-plugin-google-adsense` and add the plugin to `gatsby-config.js` like this

      
      resolve: `@isamrish/gatsby-plugin-google-adsense`,

      options: {

        googleAdClientId: "ca-pub-XXXXXXXXX",

        head: true // Optional

      }

    }

I found google tracking code in<head></head>, but adsense still dose not work.

is the error in  `gatsby-ssr.js` ?

    <script

       key={`gatsby-plugin-google-adsense`}

       ......
my site is [iNote](https://inote.xyz)

**Comment by IsAmrish** [comment]
@xiyizhou - it should work. Can you try again with updated version? Or try with head: false.
